project:
  type: website
  output-dir: sdocss

website:
  title: "website"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: mapas.qmd
        text: Mapichuelis
      - href: rutiquis.qmd
        text: Rutiquis
      - text: "Apuntes"
        menu:
          - href: https://oflora.github.io/geobotanica_apuntes
          - text: "Geobotánica"
      - blog.qmd
      - about.qmd
 #   right:
 #     - icon: telegram
 #       href: https://mastodon.com
 #     - icon: mastodon
 #       href: https://mastodon.com
    sidebar:
      contents: auto
  repo-url: https://github.com/oflora/geobotanica/
  repo-actions: [edit, issue]
  page-footer: "No seas un saco de mierda individualista."

lang: es

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true



