---
title: "Dehesa del Saler"
format: html
editor: visual
---

# Tracheophyta

```{r librerias, include=FALSE}
library(rgbif)
library(DT)
library(ggplot2)
library(dplyr)
```

```{r echo=FALSE, cache=TRUE, warning=FALSE, include=FALSE}
plantae_df <- read.csv("~/data/proyectos/heavysitou/data/tracheo_occ.csv")
plantae_df <- plantae_df[plantae_df$species != "",]

plantae_df <- dplyr::select(plantae_df, phylum, class, order, family, genus, species,
                            scientificName, acceptedScientificName,verbatimScientificName,
                            taxonRank)

plantae_df <- plantae_df[order(plantae_df$phylum,
                               plantae_df$class,
                               plantae_df$order,
                               plantae_df$family,
                               plantae_df$genus,
                               plantae_df$species),]

tracheo_df <- plantae_df[plantae_df$phylum == "Tracheophyta",]
```

```{r echo=FALSE, cache=TRUE, warning=FALSE, include=FALSE}
tracheo_e <- group_by(tracheo_df, class, family, genus, species, acceptedScientificName,
                      verbatimScientificName, taxonRank)
tracheo_e <- count(tracheo_e)

```


```{r echo=FALSE}
datatable(tracheo_e, 
          extensions = 'Buttons',
          options = list(dom = 'Blfrtip',
                         buttons = c('copy', 'csv', 'excel')), 
          filter =  "top")

```
